#!/usr/bin/env php
<?php

use TextOperation\DefaultServerWorker;
use TextOperation\Document\MemoryBackend;
use TextOperation\Websocket\OperationalTransformation;

ini_set('display_errors', 1);
error_reporting(E_ALL);
//
// $path = realpath(__DIR__ . './../../../');
// /* Path to the WordPress codebase you'd like to test. Add a backslash in the end. */
// define('ABSPATH', $path.'/' );
//
// define('DB_NAME', 'jagweb');
//
// /** MySQL database username */
// define('DB_USER', 'homestead');
//
// /** MySQL database password */
// define('DB_PASSWORD', 'secret');
//
// /** MySQL hostname */
// define('DB_HOST', 'localhost');
//
// /** Database Charset to use in creating database tables. */
// define('DB_CHARSET', 'utf8');
//
// /** The Database Collate type. Don't change this if in doubt. */
// define('DB_COLLATE', '');
//
// define( 'WPLANG', '' );
// define( 'WP_DEBUG', true);
// define( 'WP_DEBUG_DISPLAY', true);
//
// $base = '/';
//
// /* Cron tries to make an HTTP request to the blog, which always fails, because tests are run in CLI mode only */
// define( 'DISABLE_WP_CRON', true );
//
// define( 'WP_ALLOW_MULTISITE', false );
// if ( WP_ALLOW_MULTISITE ) {
//     define( 'WP_TESTS_BLOGS', 'first,second,third,fourth' );
// }
// if ( WP_ALLOW_MULTISITE && !defined('WP_INSTALLING') ) {
//     define( 'SUBDOMAIN_INSTALL', WP_TESTS_SUBDOMAIN_INSTALL );
//     define( 'MULTISITE', true );
//     define( 'DOMAIN_CURRENT_SITE', WP_TESTS_DOMAIN );
//     define( 'PATH_CURRENT_SITE', '/' );
//     define( 'SITE_ID_CURRENT_SITE', 1);
//     define( 'BLOG_ID_CURRENT_SITE', 1);
//     //define( 'SUNRISE', TRUE );
// }
//
// if (!ini_get('display_errors')) {
//     ini_set('display_errors', '0');
// }
//
// $table_prefix  = 'wp_';
//
// define( 'WP_PHP_BINARY', 'php' );
//
// /*
//  * Globalize some WordPress variables, because PHPUnit loads this file inside a function
//  * See: https://github.com/sebastianbergmann/phpunit/issues/325
//  *
//  * These are not needed for WordPress 3.3+, only for older versions
// */
// global $table_prefix, $wp_embed, $wp_locale, $_wp_deprecated_widgets_callbacks, $wp_widget_factory;
//
// // These are still needed
// global $wpdb, $current_site, $current_blog, $wp_rewrite, $shortcode_tags, $wp;
//
// define('WPMU_PLUGIN_DIR', dirname( __FILE__ ) . '/mu-plugins' );
//
// $_SERVER['SERVER_PROTOCOL'] = 'HTTP/1.1';
// $_SERVER['HTTP_HOST'] = 'localhost';
// $PHP_SELF = $GLOBALS['PHP_SELF'] = $_SERVER['PHP_SELF'] = '/index.php';
//
// // Load WordPress
// require_once ABSPATH . '/wp-settings.php';

// require_once $path . '/wp-load.php';
require __DIR__ . '/vendor/autoload.php';

$otApp = new OperationalTransformation(new DefaultServerWorker(new MemoryBackend('lorem')));

$server = new \Wrench\Server('ws://localhost:1103/', array(
    'allowed_origins'            => array(
        'mysite.localhost'
    ),
));

$server->registerApplication('sock/ot', $otApp);
$server->run();
